### ISSUE TITLE
Google Cloud Robo Test Failing.

### ISSUE THREAD

**Issue by SafwanAhmad** [SafwanAhmad/PopularMovies#1]
https://console.cloud.google.com/testlab/mobile/histories/bh.3157a4101bc5249e/executions/5217320267839612579?project=popular-movies-156309

`android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
 FATAL EXCEPTION: main
 Process: com.example.android.popularmovies, PID: 5370
 android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
 	at android.database.CursorWrapper.getString(CursorWrapper.java:114)
 	at com.example.android.popularmovies.MoviePostersFragment$1.onItemClick(MoviePostersFragment.java:131)
 	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
 	at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
 	at com.example.android.popularmovies.MoviePostersFragment$2.run(MoviePostersFragment.java:279)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:135)
 	at android.app.ActivityThread.main(ActivityThread.java:5254)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

[Snapshot](https://storage.googleapis.com/test-lab-4chkzc58ph1d6-wxj02k53w0uxz/web-build_2017-01-21T10%3A53%3A58.690Z_OqeZ/Nexus9-22-en_US-portrait/artifacts/3907b2f4.jpg)

[Activity Map](https://storage.googleapis.com/test-lab-4chkzc58ph1d6-wxj02k53w0uxz/web-build_2017-01-21T10%3A53%3A58.690Z_OqeZ/Nexus9-22-en_US-portrait/artifacts/sitemap.png)

[Video](https://storage.googleapis.com/test-lab-4chkzc58ph1d6-wxj02k53w0uxz/web-build_2017-01-21T10%3A53%3A58.690Z_OqeZ/Nexus9-22-en_US-portrait/artifacts/video.mp4)

**Comment by SafwanAhmad** [comment]
onClick performed in main fragment even when no data was available.
